# Рабочая тетрадь №2. 
## Симакин Сергей Евгеньевич.

### 1.1. Теоретический материал – Библиотека NumPy
```
    NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в Python.
    Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.
    Наиболее важные атрибуты объектов ndarray:
        ndarray.ndim - число измерений (чаще их называют "оси") массива.
        ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
        ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.
        ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.
        ndarray.itemsize - размер каждого элемента массива в байтах.
        ndarray.data - буфер, содержащий фактические элементы массива.
    Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html
```

#### **Пример 1.2.1.** 
Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
display(x)
display(x[3,1])
display(x[:,1])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

8

array([ 2,  4,  6,  8, 10])

#### **Пример 1.2.2.**
Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами
3. Создать вектор размера 10, заполненный заданным числом
4. Создать вектор со значениями от 10 до 19

In [ ]:
a = np.zeros(10)
b = np.ones(10)
c = np.full((10, ), 5)
d = np.arange(10, 20)
display(a, b, c, d)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### **Пример 1.2.3.**
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение

In [ ]:
z = np.random.random((10, 10))
zmin, zmax, zmean = z.min(), z.max(), z.mean()
display(zmin, zmax, zmean)

0.007501706703723077

0.9992898175173657

0.48937590518467516

In [ ]:
A = np.arange(25).reshape((5, 5))
display(A)
A[[0,1]] = A[[1,0]]
display(A)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### **Пример 1.2.5.**
Выяснить результат следующих выражений:
 1. 0 * np.nan
 2. np.nan == np.nan
 3. np.inf > np.nan
 4. np.nan - np.nan
 5. 0.3 == 3 * 0.1

In [ ]:
display(0 * np.nan)
display(np.nan == np.nan)
display(np.inf > np.nan)
display(np.nan - np.nan)
display(0.3 == 3 * 0.1)

nan

False

False

nan

False

#### **Пример 1.2.6.**
Отсортировать массив

In [ ]:
arr = np.array([2,1,5,3,7,4,6,8])
display(arr)
arr = np.sort(arr)
display(arr)

array([2, 1, 5, 3, 7, 4, 6, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

#### **Задание 1.3.1.**
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
matrix = np.full((64, ), 0).reshape((8, 8))
matrix[[0,2,4,6], ::2] = 1
matrix[[1,3,5,7], 1::2] = 1
matrix

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### **Задание 1.3.2.**
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [ ]:
matrix = np.full((5, 5), np.arange(5))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### **Задание 1.3.3.**
Создать массив 3x3x3 со случайными значениями

In [ ]:
arr = np.random.random((3, 3, 3))
arr

array([[[0.55552133, 0.17542965, 0.87272462],
        [0.51225432, 0.58355989, 0.27365205],
        [0.59318481, 0.76436294, 0.61891902]],

       [[0.8684512 , 0.26658943, 0.59288431],
        [0.71081145, 0.83793124, 0.82347618],
        [0.19924186, 0.84699174, 0.23152876]],

       [[0.46514839, 0.61529316, 0.20993752],
        [0.48869173, 0.77975986, 0.53620409],
        [0.86455605, 0.39667443, 0.79225917]]])

#### **Задание 1.3.4.**
Создать матрицу с 0 внутри и 1 на границах.

In [ ]:
m = 5
n = 5

matrix = np.zeros((m, n))
matrix[[0, m - 1], ::] = 1
matrix[::, [0, n - 1]] = 1
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### **Задание 1.3.5.**
Создайте массив и отсортируйте его по убыванию

In [ ]:
arr = np.random.random((10, ))
display(arr)
arr = np.sort(arr)[::-1]
display(arr)

array([0.46862021, 0.09233389, 0.70719767, 0.96331776, 0.36038863,
       0.0726689 , 0.32444261, 0.96377268, 0.32597928, 0.55673181])

array([0.96377268, 0.96331776, 0.70719767, 0.55673181, 0.46862021,
       0.36038863, 0.32597928, 0.32444261, 0.09233389, 0.0726689 ])

#### **Задание 1.3.6.**
Создайте матрицу, выведите ее форму, размер и размерность

In [ ]:
matrix = np.arange(25).reshape((5, 5))
display(matrix)
display(matrix.shape)
display(matrix.size)
display(matrix.ndim)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

(5, 5)

25

2

### 2.1. Теоретический материал – Библиотека Pandas
```
    Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких
источников.
    Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
    Библиотека pandas предоставляет две ключевые структуры данных:
        Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
        DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами
```

#### **Пример 2.2.1.**
Создать Series из списка Python, словаря Python, и массива
Numpy (установить буквенные метки для последнего).

In [ ]:
import pandas as pd

lst = [1,2,3,4,5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

display(s1)
display(s2)
display(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64

a    1
b    2
c    3
dtype: int64

a    1
b    2
c    3
d    4
e    5
dtype: int64

#### **Пример 2.2.2.**
Дано два Series. Напечатать их первые элементы и все
элементы после третьего (во втором фрейме).

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
display(s1['a'])
display(s2[0])
display(s2[3:])

1

5

3    2
4    1
dtype: int64

#### **Пример 2.2.3.**
Создайте новый фрейм данных.

In [ ]:
df = pd.DataFrame()
df['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
df['Возраст'] = [38, 25]
df['Водитель'] = [True, False]
df

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

#### **Пример 2.2.4.**
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [ ]:
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
df = pd.read_csv(url)
df.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

#### **Пример 2.2.5.**
Провести анализ датафрэйма.

```
Одна из самых простых вещей, которые мы можем сделать
после загрузки данных, – это взглянуть на первые несколько строк
с помощью метода head. На последние строки можно посмотреть с
помощью функции tail. Мы также можем взглянуть на количество
строк и столбцов: dataframe.shape. Кроме того, используя метод
describe, мы можем получить описательную статистику для любых
числовых столбцов.
```

In [ ]:
display(df.head(2))
display(df.tail(3))
display(df.shape)
display(df.describe())

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

(1313, 6)

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

#### **Пример 2.2.6.**
Выберите индивидуальные данные или срезы фрейма данных.

In [ ]:
df.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

#### **Пример 2.2.7.**
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [ ]:
df[df['PClass'] == '1st'].head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

#### **Задание 2.3.1.**
Найдите евклидово расстояние между двумя Series (точками) a и b,
не используя встроенную формулу.

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([5, 4, 3, 2, 1])

distance = np.sqrt(np.sum((s1 - s2)**2))
distance

6.324555320336759

#### **Задание 2.3.2.**
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данный можно найти
здесь: https://github.com/akmand/datasets) 

In [ ]:
ulr = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
df = pd.read_csv(ulr)
df

age         workclass  education_num      marital_status  \
0       39         State-gov             13       Never-married   
1       50  Self-emp-not-inc             13  Married-civ-spouse   
2       38           Private              9            Divorced   
3       53           Private              7  Married-civ-spouse   
4       28           Private             13  Married-civ-spouse   
...    ...               ...            ...                 ...   
45217   33           Private             13       Never-married   
45218   39           Private             13            Divorced   
45219   38           Private             13  Married-civ-spouse   
45220   44           Private             13            Divorced   
45221   35      Self-emp-inc             13  Married-civ-spouse   

              occupation   relationship   race  gender  hours_per_week  \
0           Adm-clerical  Not-in-family  White    Male              40   
1        Exec-managerial        Husband  White    Male              13   
2      Handlers-cleaners  Not-in-family  White    Male              40   
3      Handlers-cleaners        Husband  Other    Male              40   
4         Prof-specialty           Wife  Other  Female              40   
...                  ...            ...    ...     ...             ...   
45217     Prof-specialty      Own-child  White    Male              40   
45218     Prof-specialty  Not-in-family  White  Female              36   
45219     Prof-specialty        Husband  White    Male              50   
45220       Adm-clerical      Own-child  Other    Male              40   
45221    Exec-managerial        Husband  White    Male              60   

      native_country  capital income_status  
0      United-States     2174         <=50K  
1      United-States        0         <=50K  
2      United-States        0         <=50K  
3      United-States        0         <=50K  
4              Other        0         <=50K  
...              ...      ...           ...  
45217  United-States        0         <=50K  
45218  United-States        0         <=50K  
45219  United-States        0         <=50K  
45220  United-States     5455         <=50K  
45221  United-States        0          >50K  

[45222 rows x 12 columns]

#### **Задание 2.3.3.**
Проделайте с получившемся из предыдущего задания фреймом
данных те же действия, что и в примерах 2.2.5-2.2.7

In [ ]:
display(df.head(2))
display(df.tail(2))
display(df.shape)
display(df.describe())

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

age     workclass  education_num      marital_status       occupation  \
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45220    Own-child  Other   Male              40  United-States     5455   
45221      Husband  White   Male              60  United-States        0   

      income_status  
45220         <=50K  
45221          >50K

(45222, 12)

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [ ]:
df.iloc[100:104]

age         workclass  education_num      marital_status  \
100   42           Private              9  Married-civ-spouse   
101   24           Private             13       Never-married   
102   38           Private             15  Married-civ-spouse   
103   56  Self-emp-not-inc              9  Married-civ-spouse   

            occupation    relationship   race gender  hours_per_week  \
100  Handlers-cleaners         Husband  White   Male              40   
101              Sales  Other-relative  White   Male              40   
102     Prof-specialty         Husband  White   Male              40   
103      Other-service         Husband  White   Male              50   

    native_country  capital income_status  
100  United-States        0         <=50K  
101  United-States        0         <=50K  
102  United-States        0          >50K  
103          Other    -1887          >50K

In [ ]:
df[(df['age'] > 20) & (df['age'] < 30)].head(5)

age         workclass  education_num      marital_status       occupation  \
4    28           Private             13  Married-civ-spouse   Prof-specialty   
12   23           Private             13       Never-married     Adm-clerical   
15   25  Self-emp-not-inc              9       Never-married  Farming-fishing   
28   23         Local-gov             12       Never-married  Protective-serv   
32   22         State-gov             10  Married-civ-spouse    Other-service   

     relationship   race  gender  hours_per_week native_country  capital  \
4            Wife  Other  Female              40          Other        0   
12      Own-child  White  Female              30  United-States        0   
15      Own-child  White    Male              35  United-States        0   
28  Not-in-family  White    Male              52  United-States        0   
32        Husband  Other    Male              15  United-States        0   

   income_status  
4          <=50K  
12         <=50K  
15         <=50K  
28         <=50K  
32         <=50K

### 3.1. Теоретический материал – Работа с числовыми данными
```
    Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов).

    Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.
Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. 
    В зависимости от используемой функции, их можно разделить на 2 большие группы:
    1. Линейные
    2. Нелинейные
   
    При нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.

    На практике наиболее распространены следующие методы
нормализации признаков:
        • Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
```
$$X_{norm} = \frac{X-X_{min}}{X_{max}-X_{min}}$$
```
        • Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.

```
$$z = \frac{x-u}{\sigma}$$
```
    При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

```

#### **Пример 3.2.1.**
Прошкалируйте числовой признак в диапазоне между двумя значениями.

In [ ]:
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scaler = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scaler.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

#### **Пример 3.2.2.**
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [ ]:
feature = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(feature)
display(standardized)
display(standardized.mean())
display(standardized.std())

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

4.4408920985006264e-17

1.0

#### **Пример 3.2.3.**
```
Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.
```

In [ ]:
df = pd.DataFrame({'A':[14.00, 90.20, 90.95, 96.27, 91.21], \
                   'B':[103.02, 107.26, 110.35, 114.23, 114.68], \
                   'C':['big', 'small', 'big', 'small', 'small']})
df

A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

In [ ]:
df[['A', 'B']] = minmax_scaler.fit_transform(df[['A', 'B']])
df

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

#### **Задание 3.3.2.**
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)
display(df)

df[['sepal_length_cm']] = minmax_scaler.fit_transform(df[['sepal_length_cm']])
df[['sepal_width_cm']] = scaler.fit_transform(df[['sepal_width_cm']])

display(df)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]